name: sight_poc_lakehouse
version: "1.0"
config-version: 2

profile: sight_poc_lakehouse

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "logs"

models:
  sight_poc_lakehouse:
    staging:
      +materialized: view
    curated:
      +materialized: table
