hydrosat_lakehouse:
  target: hydrosat
  outputs:
    hydrosat:
      type: duckdb
      path: "{{ env_var('HYDROSAT_DUCKDB_PATH', '/tmp/hydrosat-data-lake/_dbt/hydrosat.duckdb') }}"
      threads: 4
      extensions:
        - httpfs
        - parquet
        - json
