sight_poc_lakehouse:
  target: sight_poc
  outputs:
    sight_poc:
      type: duckdb
      path: "{{ env_var('SIGHT_POC_DUCKDB_PATH', '/tmp/sight-poc-data-lake/_dbt/sight_poc.duckdb') }}"
      threads: 1
      extensions:
        - httpfs
        - parquet
        - json
