default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: commit-message-format
        name: commit message format
        entry: python3 scripts/ci/check_commit_messages.py
        language: system
        stages: [commit-msg]
